### ISSUE TITLE
对于darwin中割肉策略的疑问

### ISSUE THREAD

**Issue by BBBoobb** [SharingSource/darwin.v#2]
计算机和ai ETF，策略也太魔幻了，中间过程都不T吗，从盈利到割肉出局太可惜了，倒是5G盈利10%还一直持有，这个抓的确实准，是动量策略抓的吗？另外挺想了解一下darwin中割肉的标准是怎么样的？因为相比之下，消费/传媒似乎更加没有竞争力和想象空间

**Comment by SharingSource** [comment]
> 计算机和ai ETF，策略也太魔幻了，中间过程都不T吗，从盈利到割肉出局太可惜了，倒是5G盈利10%还一直持有，这个抓的确实准，是动量策略抓的吗？另外挺想了解一下darwin中割肉的标准是怎么样的？因为相比之下，消费/传媒似乎更加没有竞争力和想象空间

抱歉，回复晚了。

1. AI 和 游戏属于碰到系统性风险了 按道理应该是 20230621（也就是昆仑万维宣布减持的首个交易日）卖出 但是我并没有将系统风险强平操作放到 darwin 中 因为根据回测结果 长期来说 按照策略严格执行更优
另外 AI、游戏、传媒 其实今年已经买卖过一次了 我在朋友圈有发过下车时间和盈利情况（是在 darwin 发布前）分别是 +22%、+38%、+21%
darwin 上线前 当时我确实考虑过这几个标的的值博率问题 但是更担心是错过全年主线 当时看来 AI 板块有望成为 2020 酒的势头
不过无论如何 这两笔交易做得都不算好 针对此 我为策略增加了一些调整 应该不会再发生这种「从盈利到割肉出局」的局面

2. darwin 所使用的策略不看基本面

3. 主逻辑非动量相关
